baseURL = "https://rolep.netlify.com/"
languageCode = "en-us"
title = "Rashed Docs"
theme = "hyde"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[[menu.main]]
  name = "Reports"
  weight = 2
  identifier = "reports"
  url = "/reports/"
