baseURL = "https://rolep.netlify.com/"
languageCode = "en-us"
theme = "hyde"
title = "Rashed Docs"
[[menu.main]]
identifier = "reports"
name = "Reports"
url = "/reports/"
weight = 1
[permalinks]
post = "/:filename/"
[taxonomies]
tag = "tags"
